services:
  web:
    build: .
    container_name: flask_app
    environment:
      REDIS_HOST: redis
    ports:
      - '8000:8000'
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
